alex

# DS/AI: Data Science Group Assignment - Great Cormorant

**Group name:** minecraft

**Student names & numbers:**
* Gabriel Chitarliev - 98920
* Aleksandar Manev - 99052
* Alexander Atanasov - 101953

---

## Setup

**Import libraries**

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns  
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

**Load dataset**

In [3]:
df = pd.read_parquet('./bird_habitats_weather.parquet')

# Sampling

In [4]:
df.head()

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Phalacrocorax carbo,agricultural,built,coast,forest,...,day_of_year,STN,TG,TN,TX,RH,FG,UG,SQ,Q
0,50.75,5.65,2010-01-01,0.0,0,0,1.7747,0.0568,0.0,0.0616,...,1,380,-2.0,-6.1,-1.1,0.1,4.6,91.0,0.0,33.0
1,50.75,5.65,2010-01-02,25.0,25,1,1.7747,0.0568,0.0,0.0616,...,2,380,-2.1,-6.7,0.2,0.2,4.9,90.0,2.7,260.0
2,50.75,5.65,2010-01-03,3.0,3,0,1.7747,0.0568,0.0,0.0616,...,3,380,-3.9,-6.7,0.8,3.0,3.3,92.0,0.3,178.0
3,50.75,5.65,2010-01-04,0.0,0,0,1.7747,0.0568,0.0,0.0616,...,4,380,-5.4,-10.5,-3.0,0.4,3.3,89.0,0.4,218.0
4,50.75,5.65,2010-01-05,0.0,0,0,1.7747,0.0568,0.0,0.0616,...,5,380,-2.3,-4.6,-1.0,0.4,3.5,92.0,0.0,177.0

In [5]:
df.describe()

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Phalacrocorax carbo,agricultural,built,coast,forest,...,day_of_year,STN,TG,TN,TX,RH,FG,UG,SQ,Q
count,1.255876e+07,1.255876e+07,12558756,1.255876e+07,1.255876e+07,1.255876e+07,1.255876e+07,1.255876e+07,1.255876e+07,1.255876e+07,...,1.255876e+07,1.255876e+07,1.253764e+07,1.253764e+07,1.253764e+07,1.253764e+07,1.253608e+07,1.253764e+07,1.253630e+07,1.253630e+07
mean,5.223006e+01,5.532783e+00,2017-12-31 11:59:59.999999,8.067763e+00,4.330658e+00,5.143431e-02,9.452277e+00,2.404833e+00,1.302932e+00,1.621184e+00,...,1.831253e+02,2.989088e+02,1.088453e+01,6.726166e+00,1.481465e+01,2.228206e+00,4.141858e+00,8.026855e+01,5.079891e+00,1.067049e+03
min,5.075000e+01,3.350000e+00,2010-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.000000e+00,2.400000e+02,-1.270000e+01,-1.950000e+01,-6.700000e+00,0.000000e+00,0.000000e+00,2.900000e+01,0.000000e+00,2.000000e+01
25%,5.170000e+01,4.900000e+00,2013-12-31 18:00:00,0.000000e+00,0.000000e+00,0.000000e+00,5.348400e+00,7.667000e-01,0.000000e+00,1.494000e-01,...,9.200000e+01,2.600000e+02,6.400000e+00,2.600000e+00,9.300000e+00,0.000000e+00,2.600000e+00,7.400000e+01,1.200000e+00,3.340000e+02
50%,5.220000e+01,5.650000e+00,2017-12-31 12:00:00,1.000000e+00,0.000000e+00,0.000000e+00,1.056820e+01,1.559900e+00,0.000000e+00,7.092000e-01,...,1.830000e+02,2.800000e+02,1.080000e+01,6.900000e+00,1.470000e+01,1.000000e-01,3.700000e+00,8.200000e+01,4.400000e+00,9.030000e+02
75%,5.280000e+01,6.200000e+00,2021-12-31 06:00:00,6.000000e+00,2.000000e+00,0.000000e+00,1.380080e+01,3.291600e+00,0.000000e+00,2.036400e+00,...,2.740000e+02,3.300000e+02,1.580000e+01,1.120000e+01,2.030000e+01,2.400000e+00,5.200000e+00,8.800000e+01,8.200000e+00,1.674000e+03
max,5.350000e+01,7.200000e+00,2025-12-31 00:00:00,1.000400e+05,2.779000e+03,1.090000e+02,1.810460e+01,1.435380e+01,1.934870e+01,1.699850e+01,...,3.660000e+02,3.910000e+02,3.090000e+01,2.350000e+01,4.020000e+01,1.064000e+02,1.800000e+01,1.000000e+02,1.570000e+01,3.130000e+03
std,6.605211e-01,8.748856e-01,NaN,3.912502e+01,1.606794e+01,3.364980e-01,5.147907e+00,2.419758e+00,3.970215e+00,2.385737e+00,...,1.054386e+02,4.632105e+01,6.218839e+00,5.777645e+00,7.255706e+00,4.617264e+00,2.101596e+00,1.033570e+01,4.252923e+00,8.067607e+02

Filtering the data based on date

In [6]:
df_filtered = df[df['eventDate'].dt.year > 2019]

In [7]:
df_filtered.head(5)

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Phalacrocorax carbo,agricultural,built,coast,forest,...,day_of_year,STN,TG,TN,TX,RH,FG,UG,SQ,Q
3652,50.75,5.65,2020-01-01,0.0,0,0,1.7747,0.0568,0.0,0.0616,...,1,380,-0.6,-3.2,2.9,0.0,1.9,99.0,2.7,318.0
3653,50.75,5.65,2020-01-02,2.0,2,0,1.7747,0.0568,0.0,0.0616,...,2,380,3.5,-0.6,7.4,0.0,4.5,89.0,1.3,178.0
3654,50.75,5.65,2020-01-03,0.0,0,0,1.7747,0.0568,0.0,0.0616,...,3,380,7.5,3.5,9.4,4.9,5.8,92.0,0.0,71.0
3655,50.75,5.65,2020-01-04,10.0,9,1,1.7747,0.0568,0.0,0.0616,...,4,380,5.0,2.5,6.9,0.1,3.6,90.0,1.9,237.0
3656,50.75,5.65,2020-01-05,0.0,0,0,1.7747,0.0568,0.0,0.0616,...,5,380,5.9,5.2,7.0,0.0,3.0,84.0,0.0,116.0

In [8]:
df_filtered.tail(5)

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Phalacrocorax carbo,agricultural,built,coast,forest,...,day_of_year,STN,TG,TN,TX,RH,FG,UG,SQ,Q
12558751,53.5,6.55,2025-12-27,0.0,0,0,0.0353,0.0,18.4195,0.0,...,361,280,3.4,-2.4,7.2,0.0,2.2,90.0,0.5,126.0
12558752,53.5,6.55,2025-12-28,0.0,0,0,0.0353,0.0,18.4195,0.0,...,362,280,0.3,-3.2,4.4,0.0,1.4,97.0,1.7,198.0
12558753,53.5,6.55,2025-12-29,0.0,0,0,0.0353,0.0,18.4195,0.0,...,363,280,5.2,1.1,7.4,0.2,3.3,83.0,0.5,141.0
12558754,53.5,6.55,2025-12-30,0.0,0,0,0.0353,0.0,18.4195,0.0,...,364,280,3.2,-2.1,6.4,0.1,3.0,70.0,5.1,295.0
12558755,53.5,6.55,2025-12-31,0.0,0,0,0.0353,0.0,18.4195,0.0,...,365,280,4.0,-1.1,7.4,0.1,5.2,89.0,1.7,195.0

Creating the seen column

In [9]:
df_filtered['seen'] = (df_filtered['Phalacrocorax carbo'] > 0).astype(int)

splitting the data

In [11]:
X = df_filtered.drop(columns=['Phalacrocorax carbo','seen','eventDate'])

y = df_filtered['seen']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)